version: '3.3'

services:
    eco-server:
#       if you are running on a vServer you might ned this:
#       network_mode: "host"
        build: .
        ports:
            - "3000:3000/tcp"
            - "3000:3000/udp"
            - "3001:3001/tcp"
        volumes:
#            modify your volumes/paths here
#           - eco-configs:/eco/Configs
            - eco-world:/eco/Storage
            - eco-logs:/eco/Logs
        restart: 
            always

# default volumes for the container:
volumes:
    eco-world:
    eco-logs:
#   config volume you will need to create:
#   eco-configs:
#       external: true
        
